### ISSUE TITLE
Dynamically populate SELECT_EDITOR values

### ISSUE THREAD

**Issue by simonedalfior-enerj** [thomasduft/formdef#2]
Hello Thomas, 
I'd like to call a web api to obtain a list of items to populate SELECT_EDITOR values.
Is it possible?

Thanks,
Simon

**Comment by thomasduft** [comment]
Hi Simon
Yes it is possible. You can find a sample here:
- [defining the model with a dependency constructor parameter](https://github.com/thomasduft/microwf/blob/master/samples/WebClient/src/app/issue/models.ts)
- [loading dynamic select option entries and register slot](https://github.com/thomasduft/microwf/blob/0bd1ffa50e1fc1e173748041b70963299c8ba6b1/samples/WebClient/src/app/issue/issue.component.ts#L111)

It basically comes down into the following: Instead of registering a slot within the components NgModule (see [here](https://github.com/thomasduft/formdef/blob/f3f60e4622dfeb7eab60ec128f9f757f678473fa/src/app/simple/simple.module.ts#L27) as an example) you register it after you loaded the required options entries right where you create your ngForm (most likely somewhere in a component's ngOnInit).

Hope I could help you out.

Cheers Thomas

**Comment by simonedalfior-enerj** [comment]
Thanks Thomas,
it works.

Have a nice day
Simon
